FROM node:12-alpine as build

WORKDIR /usr/local/api-gateway

COPY dist-test package.json ./

RUN npm install

FROM node:12-alpine

WORKDIR /usr/local/api-gateway

COPY --from=build /usr/local/api-gateway .

RUN npm install -g jest

EXPOSE 3000

CMD ["node", "./src/index.js"]
